### PR TITLE
Edited Pref Dialog scope to persist past SideMenu

### LINKED ISSUE #67: Finish Preferences Menu
Partially started by #61

### PR DESCRIPTION
**Pull request by SpiritSeal**
Resolves #67 

Basic Template and functional structure of the Preference menu completed.

@epodol What should I put in the preference menu for now?

### CODE REVIEW

**Comment by SpiritSeal** [comment]
This is really a Post-MVP feature in almost every sense of that classification

**Comment by SpiritSeal** [comment]
Basic Boilerplate for the Preferences Menu is complete. Other issues that utilize the preference menu (before this is officially merged) should mention this issue.

**Comment by epodol** [comment]
Start with
- Toggle for AI Idea Generation

**Review by epodol — APPROVED** [review]

**Comment by SpiritSeal** [comment]
> Start with
> 
> * Toggle for AI Idea Generation

Actually implementing this will require me to split our current all-in-one generate new idea function into two separate smaller ones. I'll build the pref menu thing here, but I'm going to open a new issue for the implementation of it. I'll ask you to set up the React/ Firebase part of it that gives me two functions to work with.

**Comment by SpiritSeal** [comment]
I lied, making two new issues for these.

**Pull request merged**
